name: Deploy to Main

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch for deployment'
        required: true
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge develop into main
      run: |
        target_branch=${{ github.event.inputs.branch }}
        git checkout $target_branch
        git merge --no-ff origin/develop
        git push origin $target_branch
